# Sprint02_T05_Exploració de les dades

## Exercici 1. Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un pandas Dataframe. Explora les dades que conté, i queda’t únicament amb les columnes que consideris rellevants.

In [33]:
import pandas as pd
import numpy as np

#limito càrrega de dades per tema de memòria
pd.options.display.max_rows = 100 
df = pd.read_csv("/home/rusi/anaconda3/ejemplosruben/DelayedFlights.csv")
print(df.info())
print(df.head())
print(df.iloc[0:5,np.r_[0:20, 22]])
df02=df.iloc[:,np.r_[0:20, 22]]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB
None
   Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0           0  2008      1           3          4   2003.0        1955
1           1  2008      1           3          4    754.0         735
2           2  2008      1           3          4    628.0         620
3           4  2008      1           3          4   1829.0        1755
4           5  2008      1           3          4   1940.0        1915

   ArrTime  CRSArrTime UniqueCarrier  ...  TaxiIn TaxiOut  Cancelled  \
0   2211.0        2225            WN  ...     4.0     8.0          0
1   1002.0        1000            WN  ...     5.0    10.0          0
2    804.0         750            WN  ...     3.0    17.0          0
3   1959.0        1925            WN  ...     3.0    10.0          0
4   2121.0        2110            WN  ...     4.0    10.0          0

   CancellationCode  Diverted  CarrierDelay  WeatherDelay NASDelay  \
0                 N         0           NaN           NaN      NaN
1                 N         0           NaN           NaN      NaN
2                 N         0           NaN           NaN      NaN
3                 N         0           2.0           0.0      0.0
4                 N         0           NaN           NaN      NaN

  SecurityDelay  LateAircraftDelay
0           NaN                NaN
1           NaN                NaN
2           NaN                NaN
3           0.0               32.0
4           NaN                NaN

[5 rows x 30 columns]
   Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0           0  2008      1           3          4   2003.0        1955
1           1  2008      1           3          4    754.0         735
2           2  2008      1           3          4    628.0         620
3           4  2008      1           3          4   1829.0        1755
4           5  2008      1           3          4   1940.0        1915

   ArrTime  CRSArrTime UniqueCarrier  ...  TailNum ActualElapsedTime  \
0   2211.0        2225            WN  ...   N712SW             128.0
1   1002.0        1000            WN  ...   N772SW             128.0
2    804.0         750            WN  ...   N428WN              96.0
3   1959.0        1925            WN  ...   N464WN              90.0
4   2121.0        2110            WN  ...   N726SW             101.0

   CRSElapsedTime  AirTime  ArrDelay  DepDelay  Origin Dest Distance  \
0           150.0    116.0     -14.0       8.0     IAD  TPA      810
1           145.0    113.0       2.0      19.0     IAD  TPA      810
2            90.0     76.0      14.0       8.0     IND  BWI      515
3            90.0     77.0      34.0      34.0     IND  BWI      515
4           115.0     87.0      11.0      25.0     IND  JAX      688

   Cancelled
0          0
1          0
2          0
3          0
4          0

[5 rows x 21 columns]

## Exercici 2. Fes un informe complet del data set:
- Resumeix estadísticament les columnes d’interès
- Troba quantes dades faltants hi ha per columna
- Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...)
- Taula de les aerolínies amb més endarreriments acumulats
- Quins són els vols més llargs? I els més endarrerits?
Etc.

In [34]:
# Resumeix estadísticament les columnes d’interès
print(df02.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 21 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  Cancelled          int64
dtypes: float64(7), int64(10), object(4)
memory usage: 310.3+ MB
None

In [35]:
# Troba quantes dades faltants hi ha per columna
print(df02.isnull().sum())

Unnamed: 0              0
Year                    0
Month                   0
DayofMonth              0
DayOfWeek               0
DepTime                 0
CRSDepTime              0
ArrTime              7110
CRSArrTime              0
UniqueCarrier           0
FlightNum               0
TailNum                 5
ActualElapsedTime    8387
CRSElapsedTime        198
AirTime              8387
ArrDelay             8387
DepDelay                0
Origin                  0
Dest                    0
Distance                0
Cancelled               0
dtype: int64

In [42]:
# Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...)
df03=df02.assign(VelocitatMitjanaVol=df02["Distance"]/df02["AirTime"])
#df03=df02.assign(ArribaTard="Sí" if ["ArrDelay"]>0)
df03["ArribaTard"] = df03["ArrDelay"].apply(lambda x: "Yes" if x > 0 else "No")

print(df03)
print(df03.info())

         Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0                 0  2008      1           3          4   2003.0        1955
1                 1  2008      1           3          4    754.0         735
2                 2  2008      1           3          4    628.0         620
3                 4  2008      1           3          4   1829.0        1755
4                 5  2008      1           3          4   1940.0        1915
...             ...   ...    ...         ...        ...      ...         ...
1936753     7009710  2008     12          13          6   1250.0        1220
1936754     7009717  2008     12          13          6    657.0         600
1936755     7009718  2008     12          13          6   1007.0         847
1936756     7009726  2008     12          13          6   1251.0        1240
1936757     7009727  2008     12          13          6   1110.0        1103

         ArrTime  CRSArrTime UniqueCarrier  ...  CRSElapsedTime AirTime  \
0         2211.0        2225            WN  ...           150.0   116.0
1         1002.0        1000            WN  ...           145.0   113.0
2          804.0         750            WN  ...            90.0    76.0
3         1959.0        1925            WN  ...            90.0    77.0
4         2121.0        2110            WN  ...           115.0    87.0
...          ...         ...           ...  ...             ...     ...
1936753   1617.0        1552            DL  ...           152.0   120.0
1936754    904.0         749            DL  ...           109.0    78.0
1936755   1149.0        1010            DL  ...           143.0   122.0
1936756   1446.0        1437            DL  ...           117.0    89.0
1936757   1413.0        1418            DL  ...           135.0   104.0

         ArrDelay  DepDelay  Origin  Dest  Distance Cancelled  \
0           -14.0       8.0     IAD   TPA       810         0
1             2.0      19.0     IAD   TPA       810         0
2            14.0       8.0     IND   BWI       515         0
3            34.0      34.0     IND   BWI       515         0
4            11.0      25.0     IND   JAX       688         0
...           ...       ...     ...   ...       ...       ...
1936753      25.0      30.0     MSP   ATL       906         0
1936754      75.0      57.0     RIC   ATL       481         0
1936755      99.0      80.0     ATL   IAH       689         0
1936756       9.0      11.0     IAD   ATL       533         0
1936757      -5.0       7.0     SAT   ATL       874         0

        VelocitatMitjanaVol  ArribaTard
0                  6.982759          No
1                  7.168142         Yes
2                  6.776316         Yes
3                  6.688312         Yes
4                  7.908046         Yes
...                     ...         ...
1936753            7.550000         Yes
1936754            6.166667         Yes
1936755            5.647541         Yes
1936756            5.988764         Yes
1936757            8.403846          No

[1936758 rows x 23 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 23 columns):
 #   Column               Dtype
---  ------               -----
 0   Unnamed: 0           int64
 1   Year                 int64
 2   Month                int64
 3   DayofMonth           int64
 4   DayOfWeek            int64
 5   DepTime              float64
 6   CRSDepTime           int64
 7   ArrTime              float64
 8   CRSArrTime           int64
 9   UniqueCarrier        object
 10  FlightNum            int64
 11  TailNum              object
 12  ActualElapsedTime    float64
 13  CRSElapsedTime       float64
 14  AirTime              float64
 15  ArrDelay             float64
 16  DepDelay             float64
 17  Origin               object
 18  Dest                 object
 19  Distance             int64
 20  Cancelled            int64
 21  VelocitatMitjanaVol  float64
 22  ArribaTard           object
dtypes: float64(8), int64(10), object(5)
memory usage: 339.9+ MB
None

In [57]:
# Taula de les aerolínies amb més endarreriments acumulats
df04=df03.groupby("UniqueCarrier")[["ArrDelay"]].sum()
df04.info()
df04.sort_values(by="ArrDelay", ascending=False)

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 9E to YV
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ArrDelay  20 non-null     float64
dtypes: float64(1)
memory usage: 320.0+ bytes

                 ArrDelay
UniqueCarrier
WN             11319092.0
AA              8889066.0
UA              6733013.0
MQ              6396704.0
OO              5978936.0
XE              5176042.0
DL              4535644.0
CO              4045932.0
EV              3888131.0
YV              3691461.0
US              3571867.0
NW              3462075.0
FL              3100150.0
B6              3025749.0
OH              2675993.0
9E              2420468.0
AS              1406735.0
F9               788549.0
HA               255613.0
AQ                15814.0

In [72]:
# Quins són els vols més llargs? I els més endarrerits?
df05=df.iloc[:,np.r_[9, 14]]
filtre = df05["AirTime"] > 1
df06 = df05[filtre]
print(df06.sort_values(by="AirTime", ascending=False))
print("El vol més llarg és: " + str(df06.max()))
print("El vol més curt és: " + str(df06.min()))

        UniqueCarrier  AirTime
1488690            HA   1091.0
1367047            HA    733.0
362529             CO    664.0
556381             CO    655.0
556385             CO    654.0
...               ...      ...
186343             WN      2.0
331502             9E      2.0
56309              OO      2.0
53537              OO      2.0
53538              OO      2.0

[1928355 rows x 2 columns]
El vol més llarg és: UniqueCarrier        YV
AirTime          1091.0
dtype: object
El vol més curt és: UniqueCarrier     9E
AirTime          2.0
dtype: object

## Exercici 3. Exporta el data set net i amb les noves columnes a Excel.

In [91]:
df07 = df03.dropna()
#ValueError: This sheet is too large! Your sheet size is: 1928368, 23 Max sheet size is: 1048576, 16384
df08 = df07.iloc[:10000,:]
print(df08.info())
print(df08)
df08.to_excel("/home/rusi/Escritorio/df08.xlsx")
df08.to_csv("/home/rusi/Escritorio/df08.csv")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 0 to 10030
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           10000 non-null  int64
 1   Year                 10000 non-null  int64
 2   Month                10000 non-null  int64
 3   DayofMonth           10000 non-null  int64
 4   DayOfWeek            10000 non-null  int64
 5   DepTime              10000 non-null  float64
 6   CRSDepTime           10000 non-null  int64
 7   ArrTime              10000 non-null  float64
 8   CRSArrTime           10000 non-null  int64
 9   UniqueCarrier        10000 non-null  object
 10  FlightNum            10000 non-null  int64
 11  TailNum              10000 non-null  object
 12  ActualElapsedTime    10000 non-null  float64
 13  CRSElapsedTime       10000 non-null  float64
 14  AirTime              10000 non-null  float64
 15  ArrDelay             10000 non-null  float64
 16  DepDelay             10000 non-null  float64
 17  Origin               10000 non-null  object
 18  Dest                 10000 non-null  object
 19  Distance             10000 non-null  int64
 20  Cancelled            10000 non-null  int64
 21  VelocitatMitjanaVol  10000 non-null  float64
 22  ArribaTard           10000 non-null  object
dtypes: float64(8), int64(10), object(5)
memory usage: 1.8+ MB
None
       Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0               0  2008      1           3          4   2003.0        1955
1               1  2008      1           3          4    754.0         735
2               2  2008      1           3          4    628.0         620
3               4  2008      1           3          4   1829.0        1755
4               5  2008      1           3          4   1940.0        1915
...           ...   ...    ...         ...        ...      ...         ...
10026       25176  2008      1          10          4   1903.0        1835
10027       25179  2008      1          10          4   1441.0        1345
10028       25182  2008      1          10          4    839.0         830
10029       25184  2008      1          10          4   1720.0        1650
10030       25185  2008      1          10          4   1003.0         915

       ArrTime  CRSArrTime UniqueCarrier  ...  CRSElapsedTime AirTime  \
0       2211.0        2225            WN  ...           150.0   116.0
1       1002.0        1000            WN  ...           145.0   113.0
2        804.0         750            WN  ...            90.0    76.0
3       1959.0        1925            WN  ...            90.0    77.0
4       2121.0        2110            WN  ...           115.0    87.0
...        ...         ...           ...  ...             ...     ...
10026   2005.0        1945            WN  ...            70.0    48.0
10027   1540.0        1455            WN  ...            70.0    49.0
10028   1015.0        1020            WN  ...           110.0    84.0
10029   2004.0        1935            WN  ...           105.0    90.0
10030   1236.0        1200            WN  ...           105.0    78.0

       ArrDelay  DepDelay  Origin  Dest  Distance Cancelled  \
0         -14.0       8.0     IAD   TPA       810         0
1           2.0      19.0     IAD   TPA       810         0
2          14.0       8.0     IND   BWI       515         0
3          34.0      34.0     IND   BWI       515         0
4          11.0      25.0     IND   JAX       688         0
...         ...       ...     ...   ...       ...       ...
10026      20.0      28.0     SJC   ONT       333         0
10027      45.0      56.0     SJC   ONT       333         0
10028      -5.0       9.0     SJC   PDX       569         0
10029      29.0      30.0     SJC   PHX       621         0
10030      36.0      48.0     SJC   PHX       621         0

      VelocitatMitjanaVol  ArribaTard
0                6.982759          No
1                7.168142         Yes
2                6.776316         Yes
3                6.688312         Yes
4                7.908046         Yes
...                   ...         ...
10026            6.937500         Yes
10027            6.795918         Yes
10028            6.773810          No
10029            6.900000         Yes
10030            7.961538         Yes

[10000 rows x 23 columns]